name: Release-Auto-Pack
run-name: Packing Language Pack...
on:
  push:
  workflow_dispatch:
    branches:
      - main
  release:
    types: [published]
jobs:
  pack-all-files:
    name: Build & Pack Language Pack
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Convert cameo to shp files
        run: |
          cd ./.github/scripts/convert-png-to-shp
          npm i
          node index.js
      - name: Copy & pack cameo files
        run: |
          Copy-Item "./cameo/ra2/*.shp" -Destination "./_src_files/cameo/" -Force
          Copy-Item "./cameo/yr/*.shp" -Destination "./_src_files/cameomd/" -Force
          ./.github/bin/ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/cameo" -mix "./_src_files/language/cameo.mix" -checksum -encrypt
          ./.github/bin/ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/cameomd" -mix "./_src_files/langmd/cameomd.mix" -checksum -encrypt
        shell: pwsh
      - name: Pack langeuage pack mix files
        run: |
          ./.github/bin/ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/language" -mix "./language.mix" -checksum -encrypt
          ./.github/bin/ccmixar/ccmixar.exe pack -game ra2 -dir "./_src_files/langmd" -mix "./langmd.mix" -checksum
        shell: pwsh
      - name: Zip language pack without Chinese Audio
        run: |
          mkdir "Taunts"
          Copy-Item "./_src_files/taunts/*" -Destination "./Taunts/" -Force
          7z a "RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip" Taunts\
          7z a "RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip" .\subtitle\*
          7z a "RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip" language.mix
          7z a "RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip" langmd.mix
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip
      - name: Upload noaudio pack to artifact
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: LanguagePack-zh_hans-NoChineseAudio
          path: RedAlert2-LanguagePack-zh_hans-NoChineseAudio.zip
          retention-days: 90